# serverless.yml

cognitoUserPool:
  component: '../../../aws-cognito'
  inputs:
    region: us-west-2
    authTemplate: CUSTOM_PARAMS
    # Docs: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserPoolType.html
    # *** Pass the AWS-SDK params for Cognito User Pool directly for custom use cases ***
    userPoolParams:
      PoolName: app-users-dev
      # AliasAttributes:
      #   - email
      # AutoVerifiedAttributes:
      #   - email
      # DeviceConfiguration:
      #   ChallengeRequiredOnNewDevice: false
      #   DeviceOnlyRememberedOnUserPrompt: false
      # EmailConfiguration:
      #   ConfigurationSet: 'STRING_VALUE'
      #   EmailSendingAccount: COGNITO_DEFAULT | DEVELOPER
      #   From: 'STRING_VALUE'
      #   ReplyToEmailAddress: 'STRING_VALUE'
      #   SourceArn: 'STRING_VALUE'
      # EmailVerificationMessage: Welcome to our app, please click the link {####}
      # EmailVerificationSubject: 'Verification Email - App'
      # LambdaConfig:
      #   CreateAuthChallenge: 'STRING_VALUE'
      #   CustomMessage: 'STRING_VALUE'
      #   DefineAuthChallenge: 'STRING_VALUE'
      #   PostAuthentication: 'STRING_VALUE'
      #   PostConfirmation: 'STRING_VALUE'
      #   PreAuthentication: 'STRING_VALUE'
      #   PreSignUp: 'STRING_VALUE'
      #   PreTokenGeneration: 'STRING_VALUE'
      #   UserMigration: 'STRING_VALUE'
      #   VerifyAuthChallengeResponse: 'STRING_VALUE'
      MfaConfiguration: 'OFF'  # | ON | OPTIONAL
      Policies:
        PasswordPolicy:
          MinimumLength: 8  # 'NUMBER_VALUE'
          RequireLowercase: true  # true || false
          RequireNumbers: true  # true || false
          RequireSymbols: false  # true || false
          RequireUppercase: true  # true || false
          # TemporaryPasswordValidityDays: 'NUMBER_VALUE'
      # Schema:
      #   - AttributeDataType: String | Number | DateTime | Boolean
      #     DeveloperOnlyAttribute: true || false
      #     Mutable: true || false
      #     Name: 'STRING_VALUE'
      #     NumberAttributeConstraints: 
      #       MaxValue: 'STRING_VALUE'
      #       MinValue: 'STRING_VALUE'
      #     Required: true || false
      #     StringAttributeConstraints: 
      #       MaxLength: 'STRING_VALUE'
      #       MinLength: 'STRING_VALUE'
      # SmsAuthenticationMessage: 'STRING_VALUE'
      # SmsConfiguration:
      #   SnsCallerArn: 'STRING_VALUE'  # /* required */
      #   ExternalId: 'STRING_VALUE'
      # SmsVerificationMessage: 'STRING_VALUE'
      # UserPoolAddOns:
      #   AdvancedSecurityMode: OFF | AUDIT | ENFORCED /* required */
      UserPoolTags:
        'Owner': 'John Doe'
        'Application': 'App'
      UsernameAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK  # CONFIRM_WITH_LINK | CONFIRM_WITH_CODE
        EmailMessage: 'Welcome to our app, please click the link {####}'
        # EmailMessageByLink: 'STRING_VALUE'
        EmailSubject: 'Verification Email - App'
        # EmailSubjectByLink: 'STRING_VALUE'
        # SmsMessage: 'STRING_VALUE'
    
    # *** Pass the AWS-SDK params for User Pool Client directly for custom use cases ***
    userPoolClientParams:
      ClientName: xyz-example-dev
      GenerateSecret: false

    # *** Pass the AWS-SDK params for Cognito Identity Pool directly for custom use cases ***